name: smartcard-backend

services:
  smartcard-backend:
    build:
      context: ..
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./backend.env
    ports:
      - "127.0.0.1:4000:4000"
